
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
'''


[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  set background=dark
   call submode#enter_with('window_move', 'n', '', 's>', '<C-w>>')
   call submode#enter_with('window_move', 'n', '', 's<', '<C-w><')
   call submode#enter_with('window_move', 'n', '', 's+', '<C-w>+')
   call submode#enter_with('window_move', 'n', '', 's-', '<C-w>-')
   call submode#map('window_move', 'n', '', '>', '<C-w>>')
   call submode#map('window_move', 'n', '', '<', '<C-w><')
   call submode#map('window_move', 'n', '', '+', '<C-w>+')
   call submode#map('window_move', 'n', '', '-', '<C-w>-')

   call submode#enter_with('bufmove', 'n', '', '<Space>ss', '<Nop>')
   call submode#map('bufmove', 'n', '', 'j', '<C-w>j')
   call submode#map('bufmove', 'n', '', 'k', '<C-w>k')
   call submode#map('bufmove', 'n', '', 'l', '<C-w>l')
   call submode#map('bufmove', 'n', '', 'h', '<C-w>h')
'''

[[plugins]]
repo="honza/vim-snippets"

[[plugins]]
repo='w0rp/ale'
hook_add='''
 let g:ale_lint_on_text_changed = 0 
 let g:ale_sign_error ='✖'
 let g:ale_sign_warning = '⚠' 
 let g:ale_fix_on_save = 1
 let g:ale_fixers = {
     \'java':['google_java_format'],
     \}
 let g:ale_linters = { 
     \'python':['flake8'],
     \'php':['phpcs'],
     \}
'''

[[plugins]]
repo='vim-airline/vim-airline'
hook_add='''
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    " Options
    let g:Gtags_Auto_Map = 0
    let g:Gtags_OpenQuickfixWindow = 1
    " Keymap
    " Show definetion of function cousor word on quickfix
    nnoremap <silent> <Space>g] :<C-u>exe("Gtags ".expand('<cword>'))<CR>
    " Show reference of cousor word on quickfix
    nnoremap <silent> <Space>g[ :<C-u>exe("Gtags -r ".expand('<cword>'))<CR>
'''

# git plugin
[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"
